version = "3.11.5"
maxColumn = 120
align.preset = most
align.stripMargin = true
assumeStandardLibraryStripMargin = true
newlines.selectChains.classicCanStartWithBraceApply = false
newlines.selectChains.classicCanStartWithoutApply = true
indent.infix = [
  {
    exemptScope = []
  }
]
lineEndings = unix
newlines.selectChains.classicKeepFirst = false
newlines.avoidInResultType = true
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly
rewrite.rules = [Imports, PreferCurlyFors, RedundantBraces, RedundantParens, SortModifiers]
rewrite.imports.sort = original
rewrite.redundantBraces.stringInterpolation = true
rewrite.tokens {
  "⇒" = "=>"
  "→" = "->"
  "←" = "<-"
}
runner.dialect = scala213source3
runner.fatalWarnings = true
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.newSyntax.deprecated = true
spaces.inImportCurlyBraces = false
trailingCommas = multiple
