rules = [
  DisableSyntax
  ExplicitResultTypes
  LeakingImplicitClassVal
  NoAutoTupling
  NoValInForComprehension
  OrganizeImports
  ProcedureSyntax
  RedundantSyntax
  RemoveUnused
  TypelevelUnusedIO
  TypelevelMapSequence
  TypelevelAs
  TypelevelUnusedShowInterpolator
  TypelevelFs2SyncCompiler
  TypelevelHttp4sLiteralsSyntax
]
DisableSyntax.noVars = true
DisableSyntax.noThrows = true
DisableSyntax.noNulls = true
DisableSyntax.noReturns = true
DisableSyntax.noSemicolons = true
DisableSyntax.noWhileLoops = true
DisableSyntax.noAsInstanceOf = true
DisableSyntax.noIsInstanceOf = true
DisableSyntax.noFinalize = true
DisableSyntax.noValPatterns = true
DisableSyntax.noUniversalEquality = true
DisableSyntax.noUniversalEqualityMessage = "use === instead of =="
OrganizeImports.blankLines = Auto
OrganizeImports.coalesceToWildcardImportThreshold = 4
OrganizeImports.expandRelative = true
OrganizeImports.groupSeparately = [ByTypeGivens]
OrganizeImports.groupedImports = AggressiveMerge
OrganizeImports.groups = [
    "*"
    "re:(javax?|scala)\\."
  ]
OrganizeImports.importSelectorsOrder = SymbolsFirst
OrganizeImports.importsOrder = Ascii
OrganizeImports.preset = DEFAULT
OrganizeImports.removeUnused = true
OrganizeImports.targetDialect = Scala3
RemoveUnused.imports = false
RemoveUnused.locals = true
RemoveUnused.patternvars = true
RemoveUnused.privates = true
