addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"              % "0.11.0")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("com.timushev.sbt" % "sbt-rewarn"                % "0.1.3")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"               % "0.6.4")
addSbtPlugin("org.typelevel"    % "sbt-typelevel"             % "0.5.0-RC11")
addSbtPlugin("org.typelevel"    % "sbt-typelevel-site"        % "0.5.0-RC11")
