addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("com.timushev.sbt" % "sbt-rewarn"                % "0.2.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"               % "0.7.0")
addSbtPlugin("org.typelevel"    % "sbt-typelevel"             % "0.8.7")
addSbtPlugin("org.typelevel"    % "sbt-typelevel-scalafix"    % "0.8.7")
addSbtPlugin("org.typelevel"    % "sbt-typelevel-settings"    % "0.8.7")
addSbtPlugin("org.typelevel"    % "sbt-typelevel-site"        % "0.8.7")
