addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"              % "0.10.1")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("com.timushev.sbt" % "sbt-rewarn"                % "0.1.3")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"               % "0.6.3")
addSbtPlugin("org.typelevel"    % "sbt-typelevel"             % "0.4.12")
addSbtPlugin("org.typelevel"    % "sbt-typelevel-site"        % "0.4.12")
